config/routes.rb
Rails.application.routes.draw do
  root to: redirect('/dashboard')
  get '/dashboard', to: 'dashboard#index', as: 'dashboard'

  resources :cards
  resources :expenses
  resources :categories
  resources :transactions

  get '/card/:id/invoices', to: 'invoices#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/card.rb
class Card < ApplicationRecord
  has_many :invoices, dependent: :destroy
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :transactions, dependent: :destroy
end

app/models/expense.rb
class Expense < ApplicationRecord
  has_one :invoice, dependent: :destroy
end

app/models/icon.rb
class Icon < ApplicationRecord
end

app/models/invoice.rb
class Invoice < ApplicationRecord
  belongs_to :card
  belongs_to :expense
  has_many :transactions, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
end

app/models/revenue.rb
class Revenue < ApplicationRecord
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :category
  belongs_to :invoice
  has_many :transaction_items, dependent: :destroy

  accepts_nested_attributes_for :transaction_items, allow_destroy: true

  # add the amount to the linked invoice
  after_create do
    self.invoice.value = 50
  end
end

app/models/transaction_item.rb
class TransactionItem < ApplicationRecord
  # belongs_to :tx, class_name: "Transaction"
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :set_user, only: %i[ edit update show destroy ]

  def index
    @pagy, @cards = pagy(Card.all, items: 6)
  end

  def new
    @card = Card.new
  end
  
  def show
  end

  def create
    @card = Card.new(card_params)

    if @card.save
      redirect_to cards_path, notice: 'Cartão cadastrado com sucesso!'
    else
      redirect_to cards_path, alert: 'Ocorreu um erro no cadastro do cartão. Tente novamente!'
    end
  end

  def edit
  end

  def update
    if @card.update(card_params)
      redirect_to cards_path, notice: 'Cartão atualizado com sucesso!'
    else
      redirect_to cards_path, alert: 'Ocorreu um erro atualizar os dados do cartão. Tente novamente!'
    end
  end

  def destroy
    if @card.destroy
      redirect_to cards_path, notice: 'Cartão excluído com sucesso!'
    else
      redirect_to cards_path, alert: 'Ocorreu um erro ao remover o cartão. Tente novamente!'
    end
  end

  private

  def set_user
    @card = Card.find(params[:id])
  end

  def card_params
    params.require(:card).permit(:description, :flag, :limit, :closure, :expiration)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[ edit update destroy ]

  def index
    @pagy, @categories = pagy(Category.all, items: 6)
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)

    if @category.save
      redirect_to categories_path, notice: 'Categoria cadastrada com sucesso!'
    else
      redirect_to categories_path, alert: 'Ocorreu um erro no cadastro da categoria. Tente novamente!'
    end
  end

  def edit
  end

  def update
    if @category.update(category_params)
      redirect_to categories_path, notice: 'Categoria atualizada com sucesso!'
    else
      redirect_to categories_path, alert: 'Ocorreu um erro atualizar os dados da categoria. Tente novamente!'
    end
  end

  def destroy
    if @category.destroy
      redirect_to categories_path, notice: 'Categoria excluída com sucesso!'
    else
      redirect_to categories_path, alert: 'Ocorreu um erro ao remover a categoria. Tente novamente!'
    end
  end

  private

  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:description, :icon, :color)
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
  end
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  before_action :set_expense, only: %i[ edit update destroy ]

  def index
    @pagy, @expenses = pagy(Expense.all, items: 6)
  end

  def new
    @expense = Expense.new
  end

  def create
    @expense = Expense.new(expense_params)

    if @expense.save
      redirect_to expenses_path, notice: 'Despesa cadastrada com sucesso!'
    else
      redirect_to expenses_path, alert: 'Ocorreu um erro no cadastro do despesa. Tente novamente!'
    end
  end

  def edit
  end

  def update
    if @expense.update(expense_params)
      redirect_to expenses_path, notice: 'Despesa atualizada com sucesso!'
    else
      redirect_to expenses_path, alert: 'Ocorreu um erro atualizar os dados da despesa. Tente novamente!'
    end
  end

  def destroy
    if @expense.destroy
      redirect_to expenses_path, notice: 'Despesa excluída com sucesso!'
    else
      redirect_to expenses_path, alert: 'Ocorreu um erro ao remover a despesa. Tente novamente!'
    end
  end

  private

  def set_expense
    @expense = Expense.find(params[:id])
  end

  def expense_params
    params.require(:expense).permit(:description, :date, :value)
  end
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  def index
    @invoices = Invoice.where(card_id: params[:id])

    render json: @invoices
  end
end

app/controllers/revenues_controller.rb
class RevenuesController < ApplicationController
  before_action :set_revenue, only: %i[ edit update destroy ]

  def index
    @pagy, @revenues = pagy(Revenue.all, items: 6)
  end

  def new
    @revenue = Revenue.new
  end

  def create
    @revenue = Revenue.new(revenue_params)

    if @revenue.save
      redirect_to revenues_path, notice: 'Receita adicionado com sucesso!'
    else
      redirect_to revenues_path, alert: 'Erro ao salvar a receita. Tente novamente!'
    end
  end

  def edit
  end

  def update
    if @revenue.update(revenue_params)
      redirect_to revenues_path, notice: 'Receita atualizado com sucesso!'
    else
      redirect_to revenues_path, alert: 'Erro ao tentar atualizar os dados do receita. Tente novamente!'
    end
  end

  def destroy
    if @revenue.destroy
      redirect_to revenues_path, notice: 'Receita excluída com sucesso!'
    else
      redirect_to revenues_path, alert: 'Erro ao remover a receita. Tente novamente!'
    end
  end

  private

  def set_revenue
    @revenue = Revenue.find(params[:id])
  end

  def revenue_params
    params.require(:revenue).permit(:description, :value)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
  
  def active_link(value)
    if request.fullpath.include?("#{value}")
      "active"
    end
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
  def balance
    (revenue - expenses).round(2)
  end
  
  def revenue
    revenues = Revenue.all

    total = 0
    revenues.map {|revenue| total = total + revenue.value}

    total.round(2)
  end
  
  def expenses
    current_month_year = Date.today.strftime("%m%Y")

    transactions = Transaction.where("date LIKE '%#{current_month_year}%'")

    total = 0
    transactions.map {|transaction| total = total + transaction.value}

    total.round(2)
  end
  
  def available_credit_limit
    cards = Card.all

    total = 0 
    cards.map {|card| total = total + card.limit}
    
    (total - expenses).round(2)
  end
end

app/helpers/expense_helper.rb
module ExpenseHelper
  def expense_value(expense)
    if expense.invoice.present?
      expense.invoice&.value
    else
      expense.value
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Finances</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class='wrapper'>
      <%= render 'shared/topnavbar' %>
      <%= render 'shared/sidebar' %>
      <div class='content-wrapper'>
        <%= render 'shared/flash_messages' %>
        <%= render 'shared/content_header' %>
        <%= yield %>
        <%= turbo_frame_tag "remote_modal", target: "_top" %>
      </div>
    </div>

    <script src="https://adminlte.io/themes/v3/plugins/jquery/jquery.min.js"></script>
    <script src="https://adminlte.io/themes/v3/dist/js/adminlte.min.js?v=3.2.0"></script>
  </body>
  </body>
</html>

app/views/shared/_content_header.html.erb
<section class="content-header">
  <div class="container-fluid">
    <div class="row mb-2">
      <div class="col-sm-6">
        <h1><%= controller.controller_name.capitalize %></h1>
      </div>
      <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
          <li class="breadcrumb-item"><%= link_to "Home", root_path %></li>
          <li class="breadcrumb-item active"><%= controller.controller_name.capitalize %></li>
        </ol>
      </div>
    </div>
  </div>
</section>

app/views/shared/_flash_messages.html.erb
<% if notice.present? %>
  <div class="flash-messages">
    <div class="row">
      <div class="col-md-12">
        <div class="alert alert-success" role="alert">
          <%= notice %>
        </div>  
      </div>
    </div>
  </div>
<% end %>

<% if alert.present? %>
  <div class="flash-messages">
    <div class="row">
      <div class="col-md-12">
        <div class="alert alert-danger" role="alert">
          <%= alert %>
        </div>  
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_sidebar.html.erb
<aside class="main-sidebar sidebar-dark-primary elevation-4">
  <a href="index3.html" class="brand-link">
    <img src="//adminlte.io/themes/v3/dist/img/AdminLTELogo.png" alt="AdminLTE Logo" class="brand-image img-circle elevation-3" style="opacity: .8">
    <span class="brand-text font-weight-light">Finances</span>
  </a>

  <div class="sidebar">
    <div class="user-panel mt-3 pb-3 mb-3 d-flex">
      <div class="image">
        <img src="//adminlte.io/themes/v3/dist/img/user2-160x160.jpg" class="img-circle elevation-2" alt="User Image">
      </div>
      <div class="info">
        <%= link_to 'Robson Cavalcante', root_path, class: 'd-block' %>
      </div>
    </div>

    <nav class="mt-2">
      <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu">
        <li class="nav-item">
          <%= link_to root_path, class: "nav-link #{active_link('dashboard')}" do %>
          <i class="nav-icon bi bi-speedometer"></i>
          <p>Dashboard</p>
          <% end %>
        </li>

        <li class="nav-header mt-1">BALANÇO MENSAL</li>

        <li class="nav-item">
          <%= link_to root_path, class: "nav-link #{active_link('revenues')}" do %>
          <i class="nav-icon bi bi-graph-up-arrow w-50 h-50"></i>
          <p>Receitas</p>
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to expenses_path, class: "nav-link #{active_link('expenses')}" do %>
          <i class="nav-icon bi bi-graph-down-arrow"></i>
          <p>Despesas</p>
          <% end %>
        </li>

        <li class="nav-header mt-1">CARTÕES DE CRÉDITO</li>

        <li class="nav-item">
          <%= link_to cards_path, class: "nav-link #{active_link('cards')}" do %>
          <i class="nav-icon bi bi-credit-card-fill"></i>
          <p>Cartões</p>
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to transactions_path, class: "nav-link #{active_link('transactions')}" do %>
          <i class="nav-icon bi bi-arrow-left-right"></i>
          <p>Transações</p>
          <% end %>
        </li>

        <li class="nav-header mt-1">OUTRAS OPÇÕES</li>

        <li class="nav-item">
          <%= link_to categories_path, class: "nav-link #{active_link('categories')}" do %>
          <i class="nav-icon bi bi-tag-fill"></i>
          <p>Categorias</p>
          <% end %>
        </li>
      </ul>
    </nav>
  </div>
</aside>

app/views/shared/_topnavbar.html.erb
<nav class="main-header navbar navbar-expand navbar-white navbar-light">
   <ul class="navbar-nav">
      <li class="nav-item">
         <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <%= link_to "Home", root_path, class: "nav-link" %>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <%= link_to "Contact", root_path, class: "nav-link" %>
      </li>
   </ul>
   <ul class="navbar-nav ml-auto">
      <li class="nav-item dropdown">
         <a class="nav-link" data-toggle="dropdown" href="#">
          <i class="far fa-bell"></i>
         </a>
      </li>
   </ul>
</nav>

app/views/shared/modals/_default.html.erb
<%= turbo_frame_tag "remote_modal" do %>
  <div class="modal fade" id="shareRecipeModl" tabindex="-1" aria-labelledby="newItemRemoteModalLabel" aria-hidden="true"
    data-controller="remote-modal" data-action="turbo:before-render@document->remote-modal#hideBeforeRender">
    <div class="modal-dialog modal modal-dialog-centered" role="document">
      <div class="modal-content" id="modal_content">
        <div class="modal-header">
          <h4 class="modal-title" id="newItemRemoteModalLabel"><%= title %></h4>
          <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
        </div>
        <div class="modal-body remote_modal_body" id="remote_modal_body">
          <%= yield %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/modals/_large.html.erb
<%= turbo_frame_tag "remote_modal" do %>
  <div class="modal fade" id="shareRecipeModl" tabindex="-1" aria-labelledby="newItemRemoteModalLabel" aria-hidden="true"
    data-controller="remote-modal" data-action="turbo:before-render@document->remote-modal#hideBeforeRender">
    <div class="modal-dialog modal-lg modal-dialog-centered" role="document">
      <div class="modal-content" id="modal_content">
        <div class="modal-header">
          <h4 class="modal-title" id="newItemRemoteModalLabel"><%= title %></h4>
          <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
        </div>
        <div class="modal-body remote_modal_body" id="remote_modal_body">
          <%= yield %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/modals/_small.html.erb
<%= turbo_frame_tag "remote_modal" do %>
  <div class="modal fade" id="shareRecipeModl" tabindex="-1" aria-labelledby="newItemRemoteModalLabel" aria-hidden="true" data-controller="remote-modal" data-action="turbo:before-render@document->remote-modal#hideBeforeRender">
    <div class="modal-dialog modal modal-dialog-centered" role="document">
      <div class="modal-content" id="modal_content">
        <div class="modal-header">
          <h4 class="modal-title" id="newItemRemoteModalLabel"><%= title %></h4>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>

        <div class="modal-body remote_modal_body" id="remote_modal_body">
          <%= yield %>
        </div>
      </div>
    </div>
  </div>
<% end %>