config/routes.rb
Rails.application.routes.draw do
  root to: redirect('/dashboard')
  get '/dashboard', to: 'dashboard#index', as: 'dashboard'

  resources :cards
  resources :expenses
  resources :categories
  resources :transactions

  get '/card/:id/invoices', to: 'invoices#index'
end

app/models/card.rb
class Card < ApplicationRecord
  has_many :invoices, dependent: :destroy
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :set_user, only: %i[ edit update show destroy ]

  def index
    @pagy, @cards = pagy(Card.all, items: 6)
  end

  def new
    @card = Card.new
  end
  
  def show
  end

  def create
    @card = Card.new(card_params)

    if @card.save
      redirect_to cards_path, notice: 'Cartão cadastrado com sucesso!'
    else
      redirect_to cards_path, alert: 'Ocorreu um erro no cadastro do cartão. Tente novamente!'
    end
  end

  def edit
  end

  def update
    if @card.update(card_params)
      redirect_to cards_path, notice: 'Cartão atualizado com sucesso!'
    else
      redirect_to cards_path, alert: 'Ocorreu um erro atualizar os dados do cartão. Tente novamente!'
    end
  end

  def destroy
    if @card.destroy
      redirect_to cards_path, notice: 'Cartão excluído com sucesso!'
    else
      redirect_to cards_path, alert: 'Ocorreu um erro ao remover o cartão. Tente novamente!'
    end
  end

  private

  def set_user
    @card = Card.find(params[:id])
  end

  def card_params
    params.require(:card).permit(:description, :flag, :limit, :closure, :expiration)
  end
end

app/views/cards/_card.html.erb
<%= form_with(model: @card) do |f| %>
  <div data-turbo="false">
    <div class="row">
      <div class="col-md-12">
        <div class="form-group">
          <%= f.label :description, 'Descrição' %>
          <%= f.text_field :description, class: 'form-control', disabled: true %>
        </div>    
        <div class="form-group">
          <%= f.label :flag, 'Bandeira' %>
          <%= f.text_field :flag, class: 'form-control', disabled: true %>
        </div>
        <div class="form-group">
          <%= f.label :limit, 'Limite' %>
          <%= f.text_field :limit, class: 'form-control', disabled: true %>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-md-6">
        <div class="form-group">
          <%= f.label :closure, 'Dia de Fechamento' %>
          <%= f.text_field :closure, class: 'form-control', disabled: true %>
        </div>
      </div>
      <div class="col-md-6">
        <div class="form-group">
          <%= f.label :expiration, 'Dia do Vencimento' %>
          <%= f.text_field :expiration, class: 'form-control', disabled: true %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/cards/_form.html.erb
<%= form_with(model: card) do |f| %>
  <div data-turbo="false">
    <div class="row">
      <div class="col-md-12">
        <div class="form-group">
          <%= f.label :description, 'Descrição' %>
          <%= f.text_field :description, class: 'form-control', placeholder: 'Whey Protein - Growth' %>
        </div>    
        <div class="form-group">
          <%= f.label :flag, 'Bandeira' %>
          <%= f.text_field :flag, class: 'form-control', placeholder: 'Mastercard' %>
        </div>
        <div class="form-group">
          <%= f.label :limit, 'Limite' %>
          <%= f.text_field :limit, class: 'form-control', placeholder: 'R$ 1.540' %>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-md-6">
        <div class="form-group">
          <%= f.label :closure, 'Dia de Fechamento' %>
          <%= f.text_field :closure, class: 'form-control', placeholder: '25' %>
        </div>
      </div>
      <div class="col-md-6">
        <div class="form-group">
          <%= f.label :expiration, 'Dia do Vencimento' %>
          <%= f.text_field :expiration, class: 'form-control', placeholder: '05' %>
        </div>
      </div>
    </div>
    <%= f.submit "Salvar", class: 'btn btn-success' %>
  </div>
<% end %>

app/views/cards/edit.html.erb
<%= render "shared/modals/large", title: "Editar Cartão de Crédito" do %>
  <%= render 'form', card: @card %>
<% end %>

app/views/cards/index.html.erb
<section class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-12">
        <div class="card">
          <div class="card-header">
            <h3 class="card-title mt-2">Cartões de Crédito</h3>
            <%= link_to  '<i class="fa fa-plus"></i> Adicionar'.html_safe, new_card_path, class: 'btn btn-primary float-right', data: { turbo_frame: 'remote_modal' }%>
          </div>

          <div class="card-body">
            <table class="table table-bordered">
              <thead>
                <tr>
                  <th>Descrição</th>
                  <th>Bandeira</th>
                  <th>Limite</th>
                  <th class="text-center">Ações</th>
                </tr>
              </thead>
              <tbody>
                <% @cards.each do |card| %>
                <tr>
                  <td class="align-middle"><%= card.description %></td>
                  <td class="align-middle"><%= card.flag %></td>
                  <td class="align-middle"><%= card.limit %></td>
                  <td class="text-center">
                    <%= button_to '<i class="fas fa-eye"></i>'.html_safe, card_path(card), method: :get, class: 'rounded-circle bg-light hover-overlay', data: { turbo_frame: 'remote_modal' } %>
                    <%= button_to '<i class="fas fa-pencil-alt"></i>'.html_safe, edit_card_path(card), method: :get, class: 'rounded-circle bg-light hover-overlay', data: { turbo_frame: 'remote_modal' } %>
                    <%= button_to '<i class="fas fa-trash-alt"></i>'.html_safe, card, method: :delete, class: 'rounded-circle bg-light hover-overlay', data: { turbo_confirm: 'Você tem certeza?' } %>
                  </td>
                </tr>
                <% end %>
              </tbody>
            </table>
          </div>

          <div class="card-footer clearfix">
            <div class="row justify-content-between align-items-center">
              <%== pagy_info @pagy %>
              <%== pagy_bootstrap_nav(@pagy) %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/cards/new.html.erb
<%= render "shared/modals/large", title: "Adicionar Cartão de Crédito" do %>
  <%= render 'form', card: @card %>
<% end %>

app/views/cards/show.html.erb
<%= render "shared/modals/large", title: "Cartão de Crédito" do %>
 <%= render @card %>
<% end %>