config/routes.rb
Rails.application.routes.draw do
  root to: redirect('/dashboard')
  get '/dashboard', to: 'dashboard#index', as: 'dashboard'

  resources :cards
  resources :expenses
  resources :categories
  resources :transactions

  get '/card/:id/invoices', to: 'invoices#index'
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  def index
    @pagy, @transactions = pagy(Transaction.all, items: 10)
  end

  def show
    @items = TransactionItem.where(transaction_id: params[:id])
  end

  def new
    @transaction = Transaction.new
    @transaction.transaction_items.build
  end

  def create
    @transaction = Transactions::TransactionCreator.new(transaction_params).call
    if @transaction
      redirect_to transactions_path, notice: 'Transação cadastrada com sucesso!'
    else
      redirect_to transactions_path, alert: 'Ocorreu um erro no cadastro da transação. Tente novamente!'
    end
  end

  def edit
  end

  def update
    @transaction = Transactions::TransactionUpdate.new(transaction_params).call

    if @transaction
      redirect_to transactions_path, notice: 'Transação atualizado com sucesso!'
    else
      redirect_to transactions_path, alert: 'Erro ao atualizar os dados da transação. Tente novamente!'
    end
  end

  def destroy
    transaction = @transaction

    if @transaction.destroy
      redirect_to transactions_path, notice: 'Transação excluída com sucesso!'
    else
      redirect_to transactions_path, alert: 'Erro ao tentar remover a transação. Tente novamente!'
    end
  end

  private

  def set_user
    @transaction = Transaction.find(params[:id])
  end

  def transaction_params
    params.require(:transaction).permit(:description, :date, :value, :invoice, :category_id, :invoice_id, :card_id, 
      transaction_items_attributes: [ :id, :description, :value ]
    )
  end

end

app/views/transactions/_form.html.erb
<%= form_with(model: transaction) do |f| %>
  <div data-turbo="false">
    <div class="row">
      <div class="col-md-8">
        <div class="form-group">
          <%= f.label :description, "Descrição" %>
          <%= f.text_field :description, class: 'form-control', placeholder: 'Amazon' %>
        </div>    
      </div>
      <div class="col-md-4">
        <div class="form-group">
          <%= f.label :date, "Data" %>
          <%= f.text_field :date, class: 'form-control', placeholder: '05/12/2022' %>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-md-4">
        <div class="form-group">
          <%= f.label :card, "Cartão de Crédito" %>
          <%= f.collection_select :card_id, Card.all, :id, :description, { include_blank: 'Selecione' }, { class: 'form-select' }%>
        </div>
      </div>
      <div class="col-md-4">
        <div class="form-group">
          <%= f.label :invoice_id, "Fatura" %>
          <%= f.collection_select :invoice_id, [], [], [], { include_blank: 'Selecione' }, { class: 'form-select' } %>
          <p class="text-primary white-text mt-1" id="invoice-input-action"><i class="fas fa-plus"></i> Adicionar</p>          
        </div>
      </div>
      <div class="col-md-4">
        <div class="form-group">
          <%= f.label :category, "Categoria" %>
          <%= f.collection_select :category_id, Category.all, :id, :description, { include_blank: 'Selecione' }, { class: 'form-select' } %>
        </div>
      </div>
    </div>
    <h3>Items</h3>
    <%= f.fields_for :transaction_items do |ff| %>
      <div id="transaction-items">
        <%= render 'item_attributes', f: ff %>
      </div>
    <% end %>
    <div class="btn btn-primary" id="add-item"><i class="fas fa-plus"></i> Adicionar</div>
    <div class="btn btn-danger" id="remove-item"><i class="fas fa-times"></i> Remover</div>
      
    <div class="float-right">
      <%= link_to "Voltar", transactions_path, class: 'btn btn-secondary' %>
      <%= f.submit "Salvar", class: 'btn btn-success' %>
    </div>
  </div>
<% end %>

<%= javascript_include_tag 'transaction_items' %>
<%= javascript_include_tag 'dinamic_invoices' %>

app/views/transactions/_item_attributes.html.erb
<div class="row" id="transaction-item">
  <div class="col-md-8">
    <div class="form-group">
      <%= f.text_field :description, class: 'form-control', id: 'item-description', placeholder: 'Descrição' %>
    </div>
  </div>
  <div class="col-md-4">
    <div class="form-group">
      <%= f.text_field :value, class: 'form-control', id: 'item-value', placeholder: 'Valor' %>
    </div>
  </div>
</div>

app/views/transactions/edit.html.erb
<section class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-12">
        <div class="card">
          <div class="card-header">
            <h3 class="card-title mt-2">Nova Transação</h3>
          </div>

          <div class="card-body">
            <%= render 'form', transaction: @transaction %>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/transactions/index.html.erb
<section class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-12">
        <div class="card">
          <div class="card-header">
            <h3 class="card-title mt-2">Transações</h3>
            <%= link_to  '<i class="fa fa-plus"></i> Adicionar'.html_safe, new_transaction_path, class: 'btn btn-primary float-right', data: { turbo_frame: 'remote_modal' }%>
          </div>

          <div class="card-body">
            <table class="table table-bordered">
              <thead>
                <tr>
                  <th>Descrição</th>
                  <th>Data</th>
                  <th>Categoria</th>
                  <th>Valor</th>
                  <th class="text-center">Ações</th>
                </tr>
              </thead>
              <tbody>
                <% @transactions.each do |transaction| %>
                <tr>
                  <td class="align-middle"><%= transaction.description %></td>
                  <td class="align-middle"><%= transaction.date %></td>
                  <td class="align-middle"><%= transaction.category.description %></td>
                  <td class="align-middle"><%= transaction.value %></td>
                  <td class="text-center">
                    <%= button_to '<i class="fas fa-eye"></i>'.html_safe, transaction_path(transaction), method: :get, class: 'rounded-circle bg-light hover-overlay', data: { turbo_frame: 'remote_modal' } %>
                    <%= button_to '<i class="fas fa-pencil-alt"></i>'.html_safe, edit_transaction_path(transaction), method: :get, class: 'rounded-circle bg-light hover-overlay', data: { turbo_frame: 'remote_modal' } %>
                    <%= button_to '<i class="fas fa-trash-alt"></i>'.html_safe, transaction, method: :delete, class: 'rounded-circle bg-light hover-overlay', data: { turbo_confirm: 'Você tem certeza?' } %>
                  </td>
                </tr>
                <% end %>
              </tbody>
            </table>
          </div>

          <div class="card-footer clearfix">
            <div class="row justify-content-between align-items-center">
              <%== pagy_info @pagy %>
              <%== pagy_bootstrap_nav(@pagy) %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/transactions/new.html.erb
<section class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-12">
        <div class="card">
          <div class="card-header">
            <h3 class="card-title mt-2">Nova Transação</h3>
          </div>

          <div class="card-body">
            <%= render 'form', transaction: @transaction %>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/transactions/show.html.erb
<%= render "shared/modals/large", title: "Transação" do %>
  <div class="row">
      <dl>
        <dt>Descrição</dt>
        <dd><%= @transaction.description %></dd>
        <dt>Categoria</dt>
        <dd><%= @transaction.category.description %></dd>
        <dt>Total</dt>
        <dd><%= @transaction.value %></dd>
      </dl>
  </div>

  <legend>Items</legend>
  <div class="row">
    <div class="col-md-12">
      <table class="table table-bordered">
        <thead>
          <tr>
            <th class="col-md-9">Descrição</th>
            <th class="col-md-3">Valor</th>
          </tr>
        </thead>
        <tbody>
          <% @items.each do |item| %>
          <tr>
            <td><%= item.description %></td>
            <td>R$ <%= item.value %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
<% end %>